# Digital Ocean App Platform specification
name: repricer
region: nyc
services:
  - name: web
    git:
      repo_clone_url: https://github.com/mrwillis/repricer-monorepo.git
      branch: main
    dockerfile_path: ./apps/repricer/Dockerfile
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: /apps/repricer
    health_check:
      http_path: /health

  - name: internal-service
    dockerfile_path: ./apps/api-core/Dockerfile
    internal_ports:
      - 3001
    run_command: npm start
    git:
      repo_clone_url: https://github.com/mrwillis/repricer-monorepo.git
      branch: main
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: /apps/api-core
    health_check:
      http_path: /api/GetStatus