# Digital Ocean App Platform specification
name: repricer
region: nyc
services:
  - name: web
    environment_slug: node-js
    dockerfile_path: ./apps/repricer/Dockerfile
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    source_dir: /apps/repricer
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  - name: internal-service
    environment_slug: node-js
    dockerfile_path: ./apps/api-core/Dockerfile
    run_command: npm start
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: /apps/api-core
    health_check:
      http_path: /api/GetStatus
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3