USE repricerDb;

DROP TABLE IF EXISTS "table_biteSupplyDetails";

CREATE TABLE "table_biteSupplyDetails" (
  "Id" int NOT NULL AUTO_INCREMENT,
  "ChannelName" varchar(50) DEFAULT NULL,
  "ScrapeOn" tinyint(1) DEFAULT NULL,
  "AllowReprice" tinyint(1) DEFAULT NULL,
  "Activated" tinyint(1) DEFAULT NULL,
  "UnitPrice" decimal(10, 2) DEFAULT NULL,
  "FocusId" varchar(50) DEFAULT NULL,
  "RequestInterval" int DEFAULT NULL,
  "FloorPrice" decimal(10, 2) DEFAULT NULL,
  "MaxPrice" decimal(10, 2) DEFAULT NULL,
  "ChannelId" varchar(50) DEFAULT NULL,
  "CreatedAt" datetime DEFAULT NULL,
  "UpdatedAt" datetime DEFAULT NULL,
  "UpdatedBy" varchar(50) DEFAULT NULL,
  "LastCronTime" datetime DEFAULT NULL,
  "LastUpdateTime" datetime DEFAULT NULL,
  "LastAttemptedTime" datetime DEFAULT NULL,
  "IsNCNeeded" tinyint(1) DEFAULT NULL,
  "RepricingRule" int DEFAULT NULL,
  "RequestIntervalUnit" varchar(12) DEFAULT NULL,
  "SuppressPriceBreak" tinyint(1) DEFAULT NULL,
  "PriorityValue" int DEFAULT NULL,
  "LastCronMessage" varchar(1024) DEFAULT NULL,
  "LowestVendor" varchar(255) DEFAULT NULL,
  "LowestVendorPrice" varchar(255) DEFAULT NULL,
  "LastExistingPrice" varchar(255) DEFAULT NULL,
  "LastSuggestedPrice" varchar(255) DEFAULT NULL,
  "NextCronTime" datetime DEFAULT NULL,
  "BeatQPrice" tinyint(1) DEFAULT NULL,
  "CompeteAll" tinyint(1) DEFAULT NULL,
  "PercentageIncrease" int DEFAULT NULL,
  "SuppressPriceBreakForOne" tinyint(1) DEFAULT NULL,
  "CompareWithQ1" tinyint(1) DEFAULT NULL,
  "WaitUpdatePeriod" tinyint(1) DEFAULT NULL,
  "LastCronRun" varchar(50) DEFAULT NULL,
  "AbortDeactivatingQPriceBreak" tinyint(1) DEFAULT NULL,
  "BadgeIndicator" varchar(50) DEFAULT NULL,
  "BadgePercentage" int DEFAULT NULL,
  "LastUpdatedBy" varchar(50) DEFAULT NULL,
  "InactiveVendorId" varchar(50) DEFAULT NULL,
  "IncludeInactiveVendors" tinyint(1) DEFAULT NULL,
  "OverrideBulkRule" int DEFAULT NULL,
  "OverrideBulkUpdate" tinyint(1) DEFAULT NULL,
  "LatestPrice" int DEFAULT NULL,
  "ExecutionPriority" int DEFAULT NULL,
  "ApplyBuyBoxLogic" tinyint(1) DEFAULT NULL,
  "ApplyNcForBuyBox" tinyint(1) DEFAULT NULL,
  "MpId" int DEFAULT NULL,
  "SisterVendorId" varchar(255) DEFAULT NULL,
  "HandlingTimeFilter" varchar(50) DEFAULT NULL,
  "KeepPosition" tinyint(1) DEFAULT NULL,
  "InventoryThreshold" int DEFAULT NULL,
  "ExcludedVendors" varchar(255) DEFAULT NULL,
  "BadgePercentageDown" decimal(5, 3) DEFAULT NULL,
  "PercentageDown" decimal(5, 3) DEFAULT NULL,
  "CompeteWithNext" tinyint(1) DEFAULT NULL,
  "TriggeredByVendor" varchar(500) DEFAULT NULL,
  "IgnorePhantomBreak" tinyint(1) DEFAULT NULL,
  "OwnVendorThreshold" int DEFAULT NULL,
  "RepriceResult" varchar(128) DEFAULT NULL,
  "GetBBBadgeValue" decimal(5, 3) DEFAULT NULL,
  "GetBBShippingValue" decimal(5, 3) DEFAULT NULL,
  "GetBBBadge" tinyint(1) DEFAULT NULL,
  "GetBBShipping" tinyint(1) DEFAULT NULL,
  "CurrentInStock" tinyint(1) DEFAULT NULL,
  "CurrentInventory" int DEFAULT NULL,
  "OurLastPrice" decimal(10, 2) DEFAULT NULL,
  "MarketStateUpdatedAt" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("Id"),
  UNIQUE KEY "unique_idx_bite_supply_mpid" ("MpId"),
  KEY "idx_item_bite_supply_activated" ("Activated"),
  KEY "idx_item_bite_supply_mpid" ("MpId"),
  KEY "idx_table_bite_supply_in_stock" ("CurrentInStock")
);
