# Digital Ocean App Platform specification
name: repricer
region: nyc
services:
  - name: web
    github:
      repo: mrwillis/repricer-monorepo
      branch: main
      deploy_on_push: true
    dockerfile_path: ./apps/repricer/Dockerfile
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: apps
    health_check:
      http_path: /health

  - name: internal-service
    dockerfile_path: ./apps/api-core/Dockerfile
    internal_ports:
      - 5001
    run_command: npm start
    github:
      repo: mrwillis/repricer-monorepo
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: apps/api-core
    health_check:
      http_path: /health