# Digital Ocean App Platform specification
name: repricer
region: nyc
services:
  - name: web
    github:
      repo: mrwillis/repricer-monorepo
      branch: main
      deploy_on_push: true
    dockerfile_path: ./apps/repricer/Dockerfile
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: apps/repricer
    health_check:
      http_path: /health

  - name: internal-service
    dockerfile_path: ./apps/api-core/Dockerfile
    internal_ports:
      - 3001
    run_command: npm start
    envs:
      - key: API_KEY_SCRAPPING_BEE
        value: PLEASE_CHANGE_ME_IN_THE_UI
        scope: RUN_TIME
        encrypted: true
      - key: MANAGED_MONGO_URL
        value: PLEASE_CHANGE_ME_IN_THE_UI
        scope: RUN_TIME
        encrypted: true
      - key: SQL_HOSTNAME
        value: PLEASE_CHANGE_ME_IN_THE_UI
        scope: RUN_TIME
        encrypted: true
      - key: SQL_USERNAME
        value: PLEASE_CHANGE_ME_IN_THE_UI
        scope: RUN_TIME
        encrypted: true
      - key: SQL_PASSWORD
        value: PLEASE_CHANGE_ME_IN_THE_UI
        scope: RUN_TIME
        encrypted: true
      - key: SQL_DATABASE
        value: PLEASE_CHANGE_ME_IN_THE_UI
        scope: RUN_TIME
        encrypted: true
      - key: SQL_PORT
        value: PLEASE_CHANGE_ME_IN_THE_UI
        scope: RUN_TIME
        encrypted: true
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        encrypted: false
    github:
      repo: mrwillis/repricer-monorepo
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: apps/api-core
    health_check:
      http_path: /health