export enum VendorId {
  FRONTIER = 20722,
  TRADENT = 17357,
  MVP = 20755,
  TOPDENT = 20727,
  FIRSTDENT = 20533,
  TRIAD = 5,
}

export enum VendorName {
  FRONTIER = "FRONTIER",
  MVP = "MVP",
  TRADENT = "TRADENT",
  FIRSTDENT = "FIRSTDENT",
  TOPDENT = "TOPDENT",
  TRIAD = "TRIAD",
}

export const VendorNameLookup: Record<number, VendorName> = {
  [VendorId.FRONTIER]: VendorName.FRONTIER,
  [VendorId.TRADENT]: VendorName.TRADENT,
  [VendorId.MVP]: VendorName.MVP,
  [VendorId.TOPDENT]: VendorName.TOPDENT,
  [VendorId.FIRSTDENT]: VendorName.FIRSTDENT,
  [VendorId.TRIAD]: VendorName.TRIAD,
};

export const VendorIdLookup: Record<VendorName, VendorId> = {
  [VendorName.FRONTIER]: VendorId.FRONTIER,
  [VendorName.TRADENT]: VendorId.TRADENT,
  [VendorName.MVP]: VendorId.MVP,
  [VendorName.TOPDENT]: VendorId.TOPDENT,
  [VendorName.FIRSTDENT]: VendorId.FIRSTDENT,
  [VendorName.TRIAD]: VendorId.TRIAD,
};

export enum AlgoExecutionMode {
  V2_ONLY = "V2_ONLY",
  V1_ONLY = "V1_ONLY",
  V2_EXECUTE_V1_DRY = "V2_EXECUTE_V1_DRY",
  V1_EXECUTE_V2_DRY = "V1_EXECUTE_V2_DRY",
}

export enum AlgoPriceDirection {
  UP = "UP",
  UP_DOWN = "UP/DOWN",
  DOWN = "DOWN",
}

export enum AlgoBadgeIndicator {
  ALL = "ALL",
  BADGE = "BADGE",
}

export enum AlgoHandlingTimeGroup {
  ALL = "ALL",
  FAST_SHIPPING = "FAST_SHIPPING",
  STOCKED = "STOCKED",
  LONG_HANDLING = "LONG_HANDLING",
}

export enum AlgoPriceStrategy {
  UNIT = "UNIT",
  TOTAL = "TOTAL",
  BUY_BOX = "BUY_BOX",
}

export enum CacheKey {
  CRON_SETTINGS_LIST = "CRON_SETTINGS_LIST",
  ENV_DELAY = "ENV_DELAY",
  GLOBAL_INFO = "GLOBAL_INFO",
  PROXY_CONFIG_BY_PROVIDER_ID = "PROXY_CONFIG_BY_PROVIDER_ID",
  FILTER_CRON_DETAILS = "FILTER_CRON_DETAILS",
  SLOW_CRON_DETAILS = "SLOW_CRON_DETAILS",
  SCRAPE_CRON_DETAILS = "SCRAPE_CRON_DETAILS",
  PROXY_CONFIG_BY_PRIORITY = "PROXY_CONFIG_BY_PRIORITY",
  GET_ALL_PROXIES = "GET_ALL_PROXIES",
  PROXY_SWITCH_CRON_DETAILS = "PROXY_SWITCH_CRON_DETAILS",
  PROXY_SWITCH_CURRENT_CRON_ID = "",
  PROXY_SWITCH_CURRENT_PROXY_PRIORITY = "",
  _422_RUNNING_CACHE = "422_RUNNING_CACHE",
  OPPORTUNITY_RUNNING_CACHE = "OPPORTUNITY_RUNNING_CACHE",
  SMART_PROXY_WEB_COUNTER_CACHE = "SMART_PROXY_WEB_COUNTER_CACHE",
  SCRAPING_BEE_NON_JS_COUNTER_CACHE = "SCRAPING_BEE_NON_JS_COUNTER_CACHE",
  SCRAPING_BEE_JS_COUNTER_CACHE = "SCRAPING_BEE_JS_COUNTER_CACHE",
  BRIGHT_DATA_COUNTER_CACHE = "BRIGHT_DATA_COUNTER_CACHE",
  ENV_SETTINGS = "ENV_SETTINGS",
  IP_CONFIG = "IP_CONFIG",
}
