export interface FullProductDetailsV2 {
  ProductIdentifier: number;
  ProductId: number;
  ProductName?: string | null;
  Net32Url?: string | null;
  ScrapeOnlyActive?: number;
  LinkedScrapeOnlyCron?: string | null;
  LinkedScrapeOnlyCronId?: string | null;
  RegularCronName?: string | null;
  RegularCronId?: string | null;
  SlowCronName?: string | null;
  SlowCronId?: string | null;
  IsSlowActivated?: number;
  IsBadgeItem?: number;
  Id?: number;
  ChannelName?: string | null;
  ScrapeOn?: number;
  AllowReprice?: number;
  Activated?: number;
  UnitPrice?: string | null;
  FocusId?: string | null;
  RequestInterval?: number;
  FloorPrice?: string | null;
  MaxPrice?: string | null;
  ChannelId?: string | null;
  CreatedAt?: string | null;
  UpdatedAt?: string | null;
  UpdatedBy?: string | null;
  LastCronTime?: string | null;
  LastUpdateTime?: string | null;
  LastAttemptedTime?: string | null;
  IsNCNeeded?: number;
  RepricingRule?: number;
  RequestIntervalUnit?: string | null;
  SuppressPriceBreak?: number;
  PriorityValue?: number;
  LastCronMessage?: string | null;
  LowestVendor?: string | null;
  LowestVendorPrice?: string | null;
  LastExistingPrice?: string | null;
  LastSuggestedPrice?: string | null;
  NextCronTime?: string | null;
  BeatQPrice?: number;
  CompeteAll?: number;
  PercentageIncrease?: number;
  SuppressPriceBreakForOne?: number;
  CompareWithQ1?: number;
  WaitUpdatePeriod?: number;
  LastCronRun?: string | null;
  AbortDeactivatingQPriceBreak?: number;
  BadgeIndicator?: string | null;
  BadgePercentage?: number;
  LastUpdatedBy?: string | null;
  InactiveVendorId?: string | null;
  IncludeInactiveVendors?: number;
  OverrideBulkRule?: number;
  OverrideBulkUpdate?: number;
  LatestPrice?: number;
  ExecutionPriority?: number;
  ApplyBuyBoxLogic?: number;
  ApplyNcForBuyBox?: number;
  MpId?: number;
  SisterVendorId?: string | null;
  HandlingTimeFilter?: string | null;
  KeepPosition?: number;
  InventoryThreshold?: number;
  ExcludedVendors?: string | null;
  BadgePercentageDown?: string | null;
  PercentageDown?: string | null;
  CompeteWithNext?: number;
  TriggeredByVendor?: string | null;
  IgnorePhantomBreak?: number;
  OwnVendorThreshold?: number;
}
