use repricerDb;

DROP PROCEDURE IF EXISTS sp_UpdateTopDentDetailsByIdV3;

DELIMITER / /
CREATE PROCEDURE "sp_UpdateTopDentDetailsByIdV3" (
  IN _mpid int,
  IN _channelname varchar(50),
  IN _scrapeon boolean,
  IN _allowreprice boolean,
  IN _activated boolean,
  IN _unitprice decimal(10, 2),
  IN _focusid varchar(50),
  IN _requestinterval int,
  IN _floorprice decimal(10, 2),
  IN _maxprice decimal(10, 2),
  IN _channelid varchar(50),
  IN _updatedat varchar(50),
  IN _updatedby varchar(50),
  IN _lastcrontime varchar(50),
  IN _lastupdatetime varchar(50),
  IN _lastattemptedtime varchar(50),
  IN _isncneeded boolean,
  IN _repricingrule int,
  IN _requestintervalunit varchar(12),
  IN _suppresspricebreak boolean,
  IN _priorityvalue int,
  IN _lastcronmessage varchar(1024),
  IN _lowestvendor varchar(255),
  IN _lowestvendorprice varchar(255),
  IN _lastexistingprice varchar(255),
  IN _lastsuggestedprice varchar(255),
  IN _nextcrontime varchar(50),
  IN _beatqprice boolean,
  IN _competeall boolean,
  IN _percentageincrease int,
  IN _suppresspricebreakforone boolean,
  IN _comparewithq1 boolean,
  IN _waitupdateperiod boolean,
  IN _lastcronrun varchar(50),
  IN _abortdeactivatingqpricebreak boolean,
  IN _badgeindicator varchar(50),
  IN _badgepercentage int,
  IN _lastupdatedby varchar(50),
  IN _inactivevendorid varchar(50),
  IN _includeinactivevendors boolean,
  IN _overridebulkrule int,
  IN _overridebulkupdate boolean,
  IN _latestprice int,
  IN _executionpriority int,
  IN _applybuyboxlogic boolean,
  IN _applyncforbuybox boolean,
  IN _sisterVendorId VARCHAR(255),
  IN _handlingTimeFilter VARCHAR(50),
  IN _keepPosition boolean,
  IN _excludedVendors VARCHAR(255),
  IN _inventoryThreshold int,
  IN _repriceDown decimal(5, 3),
  IN _badgeDown decimal(5, 3),
  IN _competeWithNext boolean,
  IN _ignorePhantomBreak boolean,
  IN _ownVendorThreshold int,
  IN _getBBBadge boolean,
  IN _getBBShipping boolean,
  IN _getBBBadgeValue decimal(5, 3),
  IN _getBBShippingValue decimal(5, 3),
  IN _qBreakCount int,
  IN _qBreakDetails varchar(1024),
  IN _badge boolean
) BEGIN
select
  *
from
  table_topDentDetails
where
  MpId = _mpid;

Update table_topDentDetails
set
  ChannelName = _channelname,
  ScrapeOn = _scrapeon,
  AllowReprice = _allowreprice,
  Activated = _activated,
  UnitPrice = _unitprice,
  FocusId = _focusid,
  RequestInterval = _requestinterval,
  FloorPrice = _floorprice,
  MaxPrice = _maxprice,
  ChannelId = _channelid,
  UpdatedAt = STR_TO_DATE(_updatedat, '%Y-%m-%d %H:%i:%s'),
  UpdatedBy = _updatedby,
  LastCronTime = STR_TO_DATE(_lastcrontime, '%Y-%m-%d %H:%i:%s'),
  LastUpdateTime = STR_TO_DATE(_lastupdatetime, '%Y-%m-%d %H:%i:%s'),
  LastAttemptedTime = STR_TO_DATE(_lastattemptedtime, '%Y-%m-%d %H:%i:%s'),
  IsNCNeeded = _isncneeded,
  RepricingRule = _repricingrule,
  RequestIntervalUnit = _requestintervalunit,
  SuppressPriceBreak = _suppresspricebreak,
  PriorityValue = _priorityvalue,
  LastCronMessage = _lastcronmessage,
  LowestVendor = _lowestvendor,
  LowestVendorPrice = _lowestvendorprice,
  LastExistingPrice = _lastexistingprice,
  LastSuggestedPrice = _lastsuggestedprice,
  NextCronTime = STR_TO_DATE(_nextcrontime, '%Y-%m-%d %H:%i:%s'),
  BeatQPrice = _beatqprice,
  CompeteAll = _competeall,
  PercentageIncrease = _percentageincrease,
  SuppressPriceBreakForOne = _suppresspricebreakforone,
  CompareWithQ1 = _comparewithq1,
  WaitUpdatePeriod = _waitupdateperiod,
  LastCronRun = _lastcronrun,
  AbortDeactivatingQPriceBreak = _abortdeactivatingqpricebreak,
  BadgeIndicator = _badgeindicator,
  BadgePercentage = _badgepercentage,
  LastUpdatedBy = _lastupdatedby,
  InactiveVendorId = _inactivevendorid,
  IncludeInactiveVendors = _includeinactivevendors,
  OverrideBulkRule = _overridebulkrule,
  OverrideBulkUpdate = _overridebulkupdate,
  LatestPrice = _latestprice,
  ExecutionPriority = _executionpriority,
  ApplyBuyBoxLogic = _applybuyboxlogic,
  ApplyNcForBuyBox = _applyncforbuybox,
  SisterVendorId = _sisterVendorId,
  HandlingTimeFilter = _handlingTimeFilter,
  KeepPosition = _keepPosition,
  ExcludedVendors = _excludedVendors,
  InventoryThreshold = _inventoryThreshold,
  PercentageDown = _repriceDown,
  BadgePercentageDown = _badgeDown,
  CompeteWithNext = _competeWithNext,
  IgnorePhantomBreak = _ignorePhantomBreak,
  OwnVendorThreshold = _ownVendorThreshold,
  GetBBBadge = _getBBBadge,
  GetBBShipping = _getBBShipping,
  GetBBBadgeValue = _getBBBadgeValue,
  GetBBShippingValue = _getBBShippingValue,
  QBreakCount = _qBreakCount,
  QBreakDetails = _qBreakDetails,
  Badge = _badge
where
  MpId = _mpid;

COMMIT;

END;

/ /
