use repricerDb;

DROP PROCEDURE IF EXISTS sp_UpsertFirstDentDetailsV3;

DELIMITER / /
CREATE PROCEDURE "sp_UpsertFirstDentDetailsV3" (
  IN mpid int,
  IN channelname varchar(50),
  IN scrapeon boolean,
  IN allowreprice boolean,
  IN activated boolean,
  IN unitprice decimal(10, 2),
  IN focusid varchar(50),
  IN requestinterval int,
  IN floorprice decimal(10, 2),
  IN maxprice decimal(10, 2),
  IN channelid varchar(50),
  IN createdat varchar(50),
  IN updatedat varchar(50),
  IN updatedby varchar(50),
  IN lastcrontime varchar(50),
  IN lastupdatetime varchar(50),
  IN lastattemptedtime varchar(50),
  IN isncneeded boolean,
  IN repricingrule int,
  IN requestintervalunit varchar(12),
  IN suppresspricebreak boolean,
  IN priorityvalue int,
  IN lastcronmessage varchar(1024),
  IN lowestvendor varchar(255),
  IN lowestvendorprice varchar(255),
  IN lastexistingprice varchar(255),
  IN lastsuggestedprice varchar(255),
  IN nextcrontime varchar(50),
  IN beatqprice boolean,
  IN competeall boolean,
  IN percentageincrease int,
  IN suppresspricebreakforone boolean,
  IN comparewithq1 boolean,
  IN waitupdateperiod boolean,
  IN lastcronrun varchar(50),
  IN abortdeactivatingqpricebreak boolean,
  IN badgeindicator varchar(50),
  IN badgepercentage int,
  IN lastupdatedby varchar(50),
  IN inactivevendorid varchar(50),
  IN includeinactivevendors boolean,
  IN overridebulkrule int,
  IN overridebulkupdate boolean,
  IN latestprice int,
  IN executionpriority int,
  IN applybuyboxlogic boolean,
  IN applyncforbuybox boolean,
  IN sisterVendorId varchar(255),
  IN handlingTimeFilter varchar(50),
  IN keepPosition boolean,
  IN excludedVendors VARCHAR(255),
  IN inventoryThreshold int,
  IN _repriceDown decimal(5, 3),
  IN _badgeDown decimal(5, 3),
  IN competeWithNext boolean,
  IN _ignorePhantomBreak boolean,
  IN ownVendorThreshold int,
  IN getBBBadge boolean,
  IN getBBShipping boolean,
  IN getBBBadgeValue decimal(5, 3),
  IN getBBShippingValue decimal(5, 3),
  IN qBreakCount int,
  IN qBreakDetails varchar(1024),
  IN badge boolean
) BEGIN DECLARE EXIT
HANDLER FOR SQLEXCEPTION BEGIN
-- Rollback the transaction if an error occurs
ROLLBACK;

END;

START TRANSACTION;

INSERT INTO
  table_firstDentDetails (
    MpId,
    ChannelName,
    ScrapeOn,
    AllowReprice,
    Activated,
    UnitPrice,
    FocusId,
    RequestInterval,
    FloorPrice,
    MaxPrice,
    ChannelId,
    CreatedAt,
    UpdatedAt,
    UpdatedBy,
    LastCronTime,
    LastUpdateTime,
    LastAttemptedTime,
    IsNCNeeded,
    RepricingRule,
    RequestIntervalUnit,
    SuppressPriceBreak,
    PriorityValue,
    LastCronMessage,
    LowestVendor,
    LowestVendorPrice,
    LastExistingPrice,
    LastSuggestedPrice,
    NextCronTime,
    BeatQPrice,
    CompeteAll,
    PercentageIncrease,
    SuppressPriceBreakForOne,
    CompareWithQ1,
    WaitUpdatePeriod,
    LastCronRun,
    AbortDeactivatingQPriceBreak,
    BadgeIndicator,
    BadgePercentage,
    LastUpdatedBy,
    InactiveVendorId,
    IncludeInactiveVendors,
    OverrideBulkRule,
    OverrideBulkUpdate,
    LatestPrice,
    ExecutionPriority,
    ApplyBuyBoxLogic,
    ApplyNcForBuyBox,
    SisterVendorId,
    HandlingTimeFilter,
    KeepPosition,
    ExcludedVendors,
    InventoryThreshold,
    PercentageDown,
    BadgePercentageDown,
    CompeteWithNext,
    IgnorePhantomBreak,
    OwnVendorThreshold,
    GetBBBadge,
    GetBBShipping,
    GetBBBadgeValue,
    GetBBShippingValue,
    QBreakCount,
    QBreakDetails,
    Badge
  )
values
  (
    mpid,
    channelname,
    scrapeon,
    allowreprice,
    activated,
    unitprice,
    focusid,
    requestinterval,
    floorprice,
    maxprice,
    channelid,
    STR_TO_DATE(createdat, '%Y-%m-%d %H:%i:%s'),
    STR_TO_DATE(updatedat, '%Y-%m-%d %H:%i:%s'),
    updatedby,
    STR_TO_DATE(lastcrontime, '%Y-%m-%d %H:%i:%s'),
    STR_TO_DATE(lastupdatetime, '%Y-%m-%d %H:%i:%s'),
    STR_TO_DATE(lastattemptedtime, '%Y-%m-%d %H:%i:%s'),
    isncneeded,
    repricingrule,
    requestintervalunit,
    suppresspricebreak,
    priorityvalue,
    lastcronmessage,
    lowestvendor,
    lowestvendorprice,
    lastexistingprice,
    lastsuggestedprice,
    STR_TO_DATE(nextcrontime, '%Y-%m-%d %H:%i:%s'),
    beatqprice,
    competeall,
    percentageincrease,
    suppresspricebreakforone,
    comparewithq1,
    waitupdateperiod,
    lastcronrun,
    abortdeactivatingqpricebreak,
    badgeindicator,
    badgepercentage,
    lastupdatedby,
    inactivevendorid,
    includeinactivevendors,
    overridebulkrule,
    overridebulkupdate,
    latestprice,
    executionpriority,
    applybuyboxlogic,
    applyncforbuybox,
    sisterVendorId,
    handlingTimeFilter,
    keepPosition,
    excludedVendors,
    inventoryThreshold,
    _repriceDown,
    _badgeDown,
    competeWithNext,
    _ignorePhantomBreak,
    ownVendorThreshold,
    getBBBadge,
    getBBShipping,
    getBBBadgeValue,
    getBBShippingValue,
    qBreakCount,
    qBreakDetails,
    badge
  );

SELECT
  LAST_INSERT_ID() as updatedIdentifier;

COMMIT;

END;

/ /
