interface SqlEntity {
  ChannelName?: string;
  Activated?: number;
  MpId?: string | number;
  ChannelId?: string | number;
  UnitPrice?: number;
  FloorPrice?: number;
  MaxPrice?: number;
  IsNCNeeded?: number;
  SuppressPriceBreakForOne?: number;
  RepricingRule?: string;
  SuppressPriceBreak?: number;
  BeatQPrice?: number;
  PercentageIncrease?: number;
  CompareWithQ1?: number;
  CompeteAll?: number;
  BadgeIndicator?: string;
  BadgePercentage?: number;
  ProductName?: string;
  RegularCronId?: string;
  RegularCronName?: string;
  RequestInterval?: number;
  RequestIntervalUnit?: string;
  ScrapeOn?: number;
  AllowReprice?: number;
  FocusId?: string | number;
  Priority?: number;
  WaitUpdatePeriod?: number;
  Net32Url?: string;
  AbortDeactivatingQPriceBreak?: number;
  SisterVendorId?: string | number;
  IncludeInactiveVendors?: number;
  InactiveVendorId?: string | number;
  OverrideBulkUpdate?: number;
  OverrideBulkRule?: string;
  LatestPrice?: number;
  ExecutionPriority?: number;
  LastCronRun?: string;
  LastExistingPrice?: number;
  LastSuggestedPrice?: number;
  LastUpdatedBy?: string;
  LastAttemptedTime?: string;
  LastCronMessage?: string;
  LastCronTime?: string;
  LowestVendor?: string;
  LowestVendorPrice?: number;
  NextCronTime?: string;
  SlowCronId?: string;
  SlowCronName?: string;
  LastUpdateTime?: string;
  ApplyBuyBoxLogic?: number;
  ApplyNcForBuyBox?: number;
  IsSlowActivated?: number;
  UpdatedBy?: string;
  UpdatedAt?: string;
  HandlingTimeFilter?: string;
  KeepPosition?: number;
  ExcludedVendors?: string;
  InventoryThreshold?: number;
  PercentageDown?: number;
  BadgePercentageDown?: number;
  CompeteWithNext?: number;
  TriggeredByVendor?: string;
  IgnorePhantomBreak?: number;
  OwnVendorThreshold?: number;
}

export class OwnVendorProductDetails {
  channelName: string;
  activated: boolean;
  mpid: string | number;
  channelId: string | number;
  unitPrice: number;
  floorPrice: number;
  maxPrice: number;
  is_nc_needed: boolean;
  suppressPriceBreakForOne: boolean;
  repricingRule: string;
  suppressPriceBreak: boolean;
  beatQPrice: boolean;
  percentageIncrease: number;
  compareWithQ1: boolean;
  competeAll: boolean;
  badgeIndicator: string;
  badgePercentage: number;
  productName: string;
  cronId: string;
  cronName: string;
  requestInterval: number;
  requestIntervalUnit: string;
  scrapeOn: boolean;
  allowReprice: boolean;
  focusId: string | number;
  priority: number;
  wait_update_period: boolean;
  net32url: string;
  abortDeactivatingQPriceBreak: boolean;
  ownVendorId: string | number | null;
  sisterVendorId: string | number;
  tags: any[];
  includeInactiveVendors: boolean;
  inactiveVendorId: string | number;
  override_bulk_update: boolean;
  override_bulk_rule: string;
  latest_price: number;
  executionPriority: number;
  lastCronRun: string;
  lastExistingPrice: number;
  lastSuggestedPrice: number;
  lastUpdatedBy: string;
  last_attempted_time: string;
  last_cron_message: string;
  last_cron_time: string;
  lowest_vendor: string;
  lowest_vendor_price: number;
  next_cron_time: string;
  slowCronId: string;
  slowCronName: string;
  last_update_time: string;
  applyBuyBoxLogic: boolean;
  applyNcForBuyBox: boolean;
  isSlowActivated: boolean;
  lastUpdatedByUser: string;
  lastUpdatedOn: string;
  handlingTimeFilter: string;
  keepPosition: boolean;
  excludedVendors: string;
  inventoryThreshold: number;
  percentageDown: number;
  badgePercentageDown: number;
  competeWithNext: boolean;
  triggeredByVendor: string;
  ignorePhantomQBreak: boolean;
  ownVendorThreshold: number;
  skipReprice?: boolean;

  constructor(sqlEntity: SqlEntity) {
    this.channelName = sqlEntity["ChannelName"] || "";
    this.activated = sqlEntity["Activated"] == 1 ? true : false;
    this.mpid = sqlEntity["MpId"] || "";
    this.channelId = sqlEntity["ChannelId"] || "";
    this.unitPrice = sqlEntity["UnitPrice"] || 0;
    this.floorPrice = sqlEntity["FloorPrice"] || 0;
    this.maxPrice = sqlEntity["MaxPrice"] || 0;
    this.is_nc_needed = sqlEntity["IsNCNeeded"] == 1 ? true : false;
    this.suppressPriceBreakForOne =
      sqlEntity["SuppressPriceBreakForOne"] == 1 ? true : false;
    this.repricingRule = sqlEntity["RepricingRule"] || "";
    this.suppressPriceBreak =
      sqlEntity["SuppressPriceBreak"] == 1 ? true : false;
    this.beatQPrice = sqlEntity["BeatQPrice"] == 1 ? true : false;
    this.percentageIncrease = sqlEntity["PercentageIncrease"] || 0;
    this.compareWithQ1 = sqlEntity["CompareWithQ1"] == 1 ? true : false;
    this.competeAll = sqlEntity["CompeteAll"] == 1 ? true : false;
    this.badgeIndicator = sqlEntity["BadgeIndicator"] || "";
    this.badgePercentage = sqlEntity["BadgePercentage"] || 0;
    this.productName = sqlEntity["ProductName"] || "";
    this.cronId = sqlEntity["RegularCronId"] || "";
    this.cronName = sqlEntity["RegularCronName"] || "";
    this.requestInterval = sqlEntity["RequestInterval"] || 0;
    this.requestIntervalUnit = sqlEntity["RequestIntervalUnit"] || "";
    this.scrapeOn = sqlEntity["ScrapeOn"] == 1 ? true : false;
    this.allowReprice = sqlEntity["AllowReprice"] == 1 ? true : false;
    this.focusId = sqlEntity["FocusId"] || "";
    this.priority = sqlEntity["Priority"] || 0;
    this.wait_update_period = sqlEntity["WaitUpdatePeriod"] == 1 ? true : false;
    this.net32url = sqlEntity["Net32Url"] || "";
    this.abortDeactivatingQPriceBreak =
      sqlEntity["AbortDeactivatingQPriceBreak"] == 1 ? true : false;
    this.ownVendorId = null;
    this.sisterVendorId = sqlEntity["SisterVendorId"] || "";
    this.tags = [];
    this.includeInactiveVendors =
      sqlEntity["IncludeInactiveVendors"] == 1 ? true : false;
    this.inactiveVendorId = sqlEntity["InactiveVendorId"] || "";
    this.override_bulk_update =
      sqlEntity["OverrideBulkUpdate"] == 1 ? true : false;
    this.override_bulk_rule = sqlEntity["OverrideBulkRule"] || "";
    this.latest_price = sqlEntity["LatestPrice"] || 0;
    this.executionPriority = sqlEntity["ExecutionPriority"] || 0;
    this.lastCronRun = sqlEntity["LastCronRun"] || "";
    this.lastExistingPrice = sqlEntity["LastExistingPrice"] || 0;
    this.lastSuggestedPrice = sqlEntity["LastSuggestedPrice"] || 0;
    this.lastUpdatedBy = sqlEntity["LastUpdatedBy"] || "";
    this.last_attempted_time = sqlEntity["LastAttemptedTime"] || "";
    this.last_cron_message = sqlEntity["LastCronMessage"] || "";
    this.last_cron_time = sqlEntity["LastCronTime"] || "";
    this.lowest_vendor = sqlEntity["LowestVendor"] || "";
    this.lowest_vendor_price = sqlEntity["LowestVendorPrice"] || 0;
    this.next_cron_time = sqlEntity["NextCronTime"] || "";
    this.slowCronId = sqlEntity["SlowCronId"] || "";
    this.slowCronName = sqlEntity["SlowCronName"] || "";
    this.last_update_time = sqlEntity["LastUpdateTime"] || "";
    this.applyBuyBoxLogic = sqlEntity["ApplyBuyBoxLogic"] == 1 ? true : false;
    this.applyNcForBuyBox = sqlEntity["ApplyNcForBuyBox"] == 1 ? true : false;
    this.isSlowActivated = sqlEntity["IsSlowActivated"] == 1 ? true : false;
    this.lastUpdatedByUser = sqlEntity["UpdatedBy"] || "";
    this.lastUpdatedOn = sqlEntity["UpdatedAt"] || "";
    this.handlingTimeFilter = sqlEntity["HandlingTimeFilter"] || "";
    this.keepPosition = sqlEntity["KeepPosition"] == 1 ? true : false;
    this.excludedVendors = sqlEntity["ExcludedVendors"] || "";
    this.inventoryThreshold = sqlEntity["InventoryThreshold"] || 0;
    this.percentageDown = sqlEntity["PercentageDown"] || 0;
    this.badgePercentageDown = sqlEntity["BadgePercentageDown"] || 0;
    this.competeWithNext = sqlEntity["CompeteWithNext"] == 1 ? true : false;
    this.triggeredByVendor = sqlEntity["TriggeredByVendor"] || "";
    this.ignorePhantomQBreak =
      sqlEntity["IgnorePhantomBreak"] == 1 ? true : false;
    this.ownVendorThreshold = sqlEntity["OwnVendorThreshold"] || 0;
  }
}

export default OwnVendorProductDetails;
